adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # re_path(r'^$', adminapp.index, name='index'),
    re_path(r'^$', adminapp.ShopUserListView.as_view(), name='index'),

    re_path(r'^shopuser/create/$', adminapp.shopuser_create, name='shopuser_create'),
    re_path(r'^shopuser/update/(?P<pk>\d+)/$', adminapp.shopuser_update, name='shopuser_update'),
    re_path(r'^shopuser/delete/(?P<pk>\d+)/$', adminapp.shopuser_delete, name='shopuser_delete'),

    re_path(r'^productcategory/list/$', adminapp.productcategory_list, name='productcategory_list'),
    # re_path(r'^productcategory/create/$', adminapp.productcategory_create, name='productcategory_create'),
    re_path(r'^productcategory/create/$', adminapp.ProductCategoryCreateView.as_view(), name='productcategory_create'),
    # re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.productcategory_update, name='productcategory_update'),
    re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(),
            name='productcategory_update'),
    # re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.productcategory_delete, name='productcategory_delete'),
    re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(),
            name='productcategory_delete'),

    re_path(r'^productcategory/products/(?P<pk>\d+)/$', adminapp.productcategory_products, name='productcategory_products'),
    re_path(r'^product/create/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    re_path(r'^product/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
    # re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
    re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),

]

authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include  # Возможно стоит исправить строку
from django.conf.urls.static import static
from django.urls import path, re_path

urlpatterns = [
    path('myadmin/', include('adminapp.urls', namespace='myadmin')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('category/<int:pk>/', mainapp.category, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.category, name='category_paginator'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('infopage/<int:pk>/', cache_page(3600)(mainapp.infopage), name='infopage'),

    # re_path(r'^category/(?P<pk>\d+)/$', mainapp.category, name='category'),
    # re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    # re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    # path('contacts/', mainapp.contacts, name='contacts'),
    # re_path(r'^infopage/(?P<pk>\d+)/$', mainapp.infopage, name='infopage'),
    # path('catalog/', mainapp.catalog, name='catalog'),
    # re_path(r'^catalog/(\d+)/$', mainapp.catalog, name='catalog'),
    # path('product/', mainapp.product, name='product'),
]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

mainapp/models.py
from django.db import models


# Create your models here

class Categories(models.Model):
    name_category = models.CharField(verbose_name='Название категории', max_length=128, unique=True)
    header_category = models.CharField(verbose_name='Заголовок категории', max_length=128, blank=True)
    description_category = models.TextField(verbose_name='Описание категории', blank=True)
    show_in_main_menu = models.BooleanField(verbose_name='Выводить страницу в главном меню?', default=False)
    is_active = models.BooleanField(db_index=True, verbose_name='Показывать категорию', default=True)

    def __str__(self):
        return self.name_category

    class Meta:
        verbose_name_plural = 'Категории товаров'
        verbose_name = 'Категория'
        ordering = ['is_active', 'name_category']


class Products(models.Model):
    name_product = models.CharField(verbose_name='Название товара', max_length=128)
    description_product = models.TextField(verbose_name='Описание товара', blank=True)
    # предварительно pip install pillow
    image_product = models.ImageField(upload_to='images_products', blank=True, default='images_products/no_image.jpg')
    quantity = models.PositiveIntegerField(verbose_name='Кол-во на складе', null=False, default=10)
    price_product = models.PositiveIntegerField(verbose_name='Цена товара', null=False)  # цена больше 0 и без копеек
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    is_new = models.BooleanField(db_index=True, verbose_name='Новый товар', default=False)
    is_discount = models.BooleanField(db_index=True, verbose_name='Товар со скидкой', default=False)
    is_popular = models.BooleanField(db_index=True, verbose_name='Популярный товар', default=False)
    is_exclusive = models.BooleanField(db_index=True, verbose_name='Эксклюзивный товар', default=False)
    is_active = models.BooleanField(db_index=True, verbose_name='Показывать товар', default=True)

    class Meta:
        verbose_name_plural = 'Товары'
        verbose_name = 'Товар'
        ordering = ['is_active', 'name_product']

    def __str__(self):
        return self.name_product

    @staticmethod
    def get_items():
        return Products.objects.filter(is_active=True).order_by('category', 'name_product')


class InfoPages(models.Model):
    name_page = models.CharField(verbose_name='Название страницы', max_length=128, unique=True)
    header_page = models.CharField(verbose_name='Заголовок страницы', max_length=128, blank=True)
    content_page = models.TextField(verbose_name='Контент страницы', blank=True, default='<p></p>')
    show_in_main_menu = models.BooleanField(db_index=True, verbose_name='Выводить страницу в главном меню?', default=False)
    order_in_menu = models.PositiveIntegerField(verbose_name='Номер в меню', default=0)

    class Meta:
        verbose_name_plural = 'Информационные страницы'
        verbose_name = 'Инфостраница'
        ordering = ['name_page']

    def __str__(self):
        return self.name_page

mainapp/views.py
import random
from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from itertools import chain

from .models import Categories, Products, InfoPages


# Create your views here

# main_menu = [
#     {'href': 'category/1/', 'name': 'Смартфоны'},
#     {'href': '#', 'name': 'Оплата'},
#     {'href': '#', 'name': 'Доставка'},
#     {'href': 'contacts', 'name': 'Контакты'}
# ]

# def main_menu():
#     categories = Categories.objects.filter(show_in_main_menu=True)
#     info_pages = InfoPages.objects.filter(show_in_main_menu=True)
#     main_menu = list(chain(categories, info_pages.order_by('order_in_menu')))
#     return main_menu

def main_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            categories = Categories.objects.filter(show_in_main_menu=True)
            info_pages = InfoPages.objects.filter(show_in_main_menu=True)
            links_menu = list(chain(categories, info_pages.order_by('order_in_menu')))
            cache.set(key, links_menu)
        return links_menu
    else:
        categories = Categories.objects.filter(show_in_main_menu=True)
        info_pages = InfoPages.objects.filter(show_in_main_menu=True)
        links_menu = list(chain(categories, info_pages.order_by('order_in_menu')))
        return links_menu


# def footer_menu():
# #     info_pages = InfoPages.objects.all()
# #     return info_pages

def footer_menu():
    if settings.LOW_CACHE:
        key = 'links_footer_menu'
        links_footer_menu = cache.get(key)
        if links_footer_menu is None:
            links_footer_menu = info_pages = InfoPages.objects.all()
            cache.set(key, links_footer_menu)
        return links_footer_menu
    else:
        return InfoPages.objects.all()


# def get_categories():  # получаем все объекты категорий
#     return Categories.objects.filter(is_active=True)

def get_categories():
    if settings.LOW_CACHE:
        key = 'links_categories'
        links_categories = cache.get(key)
        if links_categories is None:
            links_categories = Categories.objects.filter(is_active=True)
            cache.set(key, links_categories)
        return links_categories
    else:
        return Categories.objects.filter(is_active=True)


# def get_products():  # получаем все объекты товаров
#     return Products.objects.filter(is_active=True)

def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Products.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Products.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')  # из юзера достаем корзину
    else:
        return []


def get_hot_product(request):
    return random.choice(Products.objects.all())


def main(request):
    new_products = Products.objects.filter(is_active=True, is_new=True)
    popular_products = Products.objects.filter(is_active=True, is_popular=True)
    exclusive_products = Products.objects.filter(is_active=True, is_exclusive=True)

    content = {
        'title': 'Главная страница магазина',
        'main_menu': main_menu,
        'info_pages': footer_menu(),
        'products': get_products(),
        'new_products': new_products,
        'popular_products': popular_products,
        'exclusive_products': exclusive_products,
    }
    return render(request, 'mainapp/index.html', context=content)


# def catalog(request):
#     content = {
#         'title': 'Каталог товаров',
#         'header1': 'Как определять категорию? Чтобы загружать соответствующие заголовки и товары.',
#         'main_menu': main_menu,
#         'categories': get_categories(),
#         'products': get_products()
#     }
#     return render(request, 'mainapp/catalog.html', content)

def category(request, pk, page=1):
    pk = int(pk)
    if pk == 1:  # если категория (Все модели с pk = 1), то выводим все товары
        current_category = Categories.objects.get(pk=1)
        # current_category = get_object_or_404(Categories, pk=1)
        products_category = Products.objects.filter(is_active=True)
    else:  # по primary key выводим товары этой категории
        current_category = Categories.objects.filter(pk=pk).first()
        products_category = Products.objects.filter(category=pk, is_active=True)

    paginator = Paginator(products_category, 15)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    content = {
        'title': current_category.header_category,
        'header1': current_category.header_category,
        'main_menu': main_menu(),
        'info_pages': footer_menu(),
        'categories': get_categories(),
        'category': current_category,
        'products': products_paginator,
    }
    return render(request, 'mainapp/catalog.html', content)


def product(request, pk):
    product = Products.objects.get(pk=pk, is_active=True)
    # выбираем похожие товары по категории, исключая текущий товар
    same_products = Products.objects.filter(category=product.category, is_active=True).exclude(pk=pk)
    content = {
        'title': product.name_product,
        'header1': product.name_product,
        'product': product,
        'same_products': same_products,
        'main_menu': main_menu(),
        'info_pages': footer_menu(),
        'categories': get_categories(),
        'products': get_products(),
    }
    return render(request, 'mainapp/product.html', context=content)


def contacts(request):
    content = {
        'title': 'Контакты интернет-магазина MyPhone',
        'header1': 'Контакты магазина',
        'main_menu': main_menu(),
        'info_pages': footer_menu(),
    }
    return render(request, 'mainapp/contacts.html', context=content)


def infopage(request, pk):
    current_page = InfoPages.objects.filter(pk=pk).first()
    content = {
        'page': current_page,
        'title': current_page.header_page,
        'main_menu': main_menu(),
        'info_pages': footer_menu(),
    }
    return render(request, 'mainapp/infopage.html', context=content)

mainapp/templates/mainapp/includes/inc_2_banners.html
<!-- Exclusive products -->
<div class="exclusive_products">
    <div class="exclusive_products_two_blocks">
        <div class="exclusive_products_block1">
            <div class="exclusive_products_block_textarea padding_site">
                <span class="exclusive_products_block_textarea_mini_title">Эксклюзив</span>
                <p class="exclusive_products_block_textarea_main_title">iPhone XR Red</p>
                <p class="exclusive_products_block_textarea_text">12 лет вместе с (RED) мы поддерживаем программы,
                    препятствующие ВИЧ.</p>
                <a href="/product/12/" class="exclusive_products_block_textarea_button">Подробнее ></a>
            </div>
        </div>
        <div class="exclusive_products_block2">
            <div class="exclusive_products_block_textarea padding_site">
                <span class="exclusive_products_block_textarea_mini_title">Эксклюзив</span>
                <p class="exclusive_products_block_textarea_main_title">Редкие цвета</p>
                <p class="exclusive_products_block_textarea_text">Уникальные расцветки: золото, серый космос, розовое
                    золото и черный сапфир.</p>
                <a href="/product/10/" class="exclusive_products_block_textarea_button">Посмотреть ></a>
            </div>
        </div>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_footer_menu.html
<!--div class="footer_useful_info">
    <p class="footer_useful_info_title">Полезная информация</p>
    <ul class="footer_useful_info_menu">
        <li class="footer_useful_info_menu_li"><a href="#" class="footer_useful_info_menu_a">Оплата</a></li>
        <li class="footer_useful_info_menu_li"><a href="#" class="footer_useful_info_menu_a">Личный кабинет</a></li>
        <li class="footer_useful_info_menu_li"><a href="#" class="footer_useful_info_menu_a">Доставка</a></li>
        <li class="footer_useful_info_menu_li"><a href="#" class="footer_useful_info_menu_a">Условия возврата</a></li>
        <li class="footer_useful_info_menu_li"><a href="#" class="footer_useful_info_menu_a">Гарантия</a></li>
        <li class="footer_useful_info_menu_li"><a href="#" class="footer_useful_info_menu_a">Скидки и бонусы</a></li>
    </ul>
</div-->

<div class="footer_useful_info">
    <p class="footer_useful_info_title">Полезная информация</p>
    <ul class="footer_useful_info_menu">
        {% if user.is_authenticated %}
            <li class="footer_useful_info_menu_li"><a href="{% url 'auth:update' %}" class="footer_useful_info_menu_a">Изменить данные</a></li>
        {% else %}
            <li class="footer_useful_info_menu_li"><a href="{% url 'authapp:login' %}" class="footer_useful_info_menu_a">Авторизоваться</a></li>
        {% endif %}
        {% for page in info_pages %}
        <li class="footer_useful_info_menu_li"><a href="{% url 'main:infopage' page.pk %}" class="footer_useful_info_menu_a{% if request.resolver_match.url_name == 'infopage' and request.resolver_match.kwargs.pk|add:0 == page.pk %}_current{% endif %}">{{ page.name_page }}</a></li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc_main_menu.html
{% load staticfiles %}
<header class="header">
    <a href="{% url 'main:main' %}" class="header_logo_a" title="Вернуться на Главную">
        <img src="{% static 'images/logo_myphone.png' %}" alt="Логотип компании Interior" class="header_logo_img">
    </a>
    <nav class="header_menu_search">
        <ul class="header_menu">
            {% for page in main_menu %}
            <li class="header_menu_li">
                {% if page.name_category == 'Все модели' %}
                <a href="{% url 'main:category' page.pk %}"
                   class="header_menu_a{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk|add:0 == page.pk %}_current
                   {% endif %}">Смартфоны</a>
                {% else %}
                <a href="{% url 'main:infopage' page.pk %}"
                   class="header_menu_a{% if request.resolver_match.url_name == 'infopage' and request.resolver_match.kwargs.pk|add:0 == page.pk %}_current
                   {% endif %}">{{ page.name_page }}</a>
                {% endif %}
            </li>
            {% endfor %}

            {% if user.is_superuser %}
            <li class="header_menu_li"><a href="{% url 'adminapp:index' %}" class="header_menu_a">админка</a></li>
            {% endif %}

            {% if user.is_authenticated %}
            <li class="header_menu_li">
                <a href="{% url 'auth:update' %}" class="header_menu_a">{{ user.first_name|default:'Пользователь' }} ▼</a>
                <ul class="header_menu_dropdown_menu">
                    <li class="header_menu_dropdown_menu_li">
                        <a class="header_menu_dropdown_menu_a" href="{% url 'ordersapp:orders_list' %}" class="header_menu_a">Заказы</a>
                    </li>
                </ul>
            </li>
            <li class="header_menu_li"><a href="{% url 'authapp:logout' %}" class="header_menu_a">Выйти</a></li>
            {% else %}
            <li class="header_menu_li"><a href="{% url 'authapp:login' %}" class="header_menu_a">Войти</a></li>
            {% endif %}
        </ul>
        <div class="header_basket">
            <a href="{% url 'basket:index' %}" class="header_basket_a" title="Перейти в корзину">
                <i class="fas fa-shopping-basket"></i>
                {% if basket %}
                <sup class="header_basket_a_span">{{ basket.0.get_total_quantity }} шт. = {{ basket.0.get_total_cost }} руб.</sup>
                {% endif %}
            </a>
        </div>
    </nav>
</header>