adminapp/urls.py
from django.urls import path, re_path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    # re_path(r'^$', adminapp.index, name='index'),
    re_path(r'^$', adminapp.ShopUserListView.as_view(), name='index'),

    re_path(r'^shopuser/create/$', adminapp.shopuser_create, name='shopuser_create'),
    re_path(r'^shopuser/update/(?P<pk>\d+)/$', adminapp.shopuser_update, name='shopuser_update'),
    re_path(r'^shopuser/delete/(?P<pk>\d+)/$', adminapp.shopuser_delete, name='shopuser_delete'),

    re_path(r'^productcategory/list/$', adminapp.productcategory_list, name='productcategory_list'),
    # re_path(r'^productcategory/create/$', adminapp.productcategory_create, name='productcategory_create'),
    re_path(r'^productcategory/create/$', adminapp.ProductCategoryCreateView.as_view(), name='productcategory_create'),
    # re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.productcategory_update, name='productcategory_update'),
    re_path(r'^productcategory/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(),
            name='productcategory_update'),
    # re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.productcategory_delete, name='productcategory_delete'),
    re_path(r'^productcategory/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(),
            name='productcategory_delete'),

    re_path(r'^productcategory/products/(?P<pk>\d+)/$', adminapp.productcategory_products, name='productcategory_products'),
    re_path(r'^product/create/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    re_path(r'^product/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    re_path(r'^product/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
    # re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
    re_path(r'^product/read/(?P<pk>\d+)/$', adminapp.ProductDetailView.as_view(), name='product_read'),

]

authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include  # Возможно стоит исправить строку
from django.conf.urls.static import static
from django.urls import path, re_path

urlpatterns = [
    path('myadmin/', include('adminapp.urls', namespace='myadmin')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('category/<int:pk>/', mainapp.category, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.category, name='category_paginator'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('infopage/<int:pk>/', cache_page(3600)(mainapp.infopage), name='infopage'),

    # re_path(r'^category/(?P<pk>\d+)/$', mainapp.category, name='category'),
    # re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    # re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    # path('contacts/', mainapp.contacts, name='contacts'),
    # re_path(r'^infopage/(?P<pk>\d+)/$', mainapp.infopage, name='infopage'),
    # path('catalog/', mainapp.catalog, name='catalog'),
    # re_path(r'^catalog/(\d+)/$', mainapp.catalog, name='catalog'),
    # path('product/', mainapp.product, name='product'),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms import HiddenInput, ModelForm
from django import forms
from authapp.models import ShopUser
from mainapp.models import Categories, Products


class ShopUserAdminCreateForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''  # здесь можно добавить свой текст помощи, который будет выводиться на форме

    def clean_age(self):  # все валидаторы должны начинаться с clean
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data  # все валидаторы должны возвращать данные


class ShopUserAdminUpdateForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'avatar',
                  'password', 'is_superuser', 'is_active')  # без поля password невозможно сохранить изменения

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''  # очищаем текст помощи
            if field_name == 'password':
                field.widget = HiddenInput()  # скрываем поле пароля для конфиденциальности

    def clean_age(self):  # валидатор/проверка возраста
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError("Вы слишком молоды!")

        return data


class CategoriesAdminUpdateForm(ModelForm):
    # Чтобы избежать проблем с валидацией мы задали аргумент required=False
    discount = forms.IntegerField(label='Скидка на товары', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = Categories
        # fields = '__all__'
        # exclude кортеж с исключенными из отображения полями
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductAdminUpdateForm(ModelForm):
    class Meta:
        model = Products
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection
from django.db.models import F

from adminapp.forms import ShopUserAdminCreateForm, ShopUserAdminUpdateForm, CategoriesAdminUpdateForm, \
    ProductAdminUpdateForm
from authapp.models import ShopUser
from mainapp.models import Categories, Products


# Create your views here.

# @user_passes_test(lambda x: x.is_superuser)
# def index(request):
#     object_list = ShopUser.objects.all()
#     content = {
#         'title': 'админка/пользователи',
#         'object_list': object_list,
#     }
#     return render(request, 'adminapp/index.html', content)

class ShopUserListView(ListView):
    model = ShopUser

    # template_name = 'adminapp/index.html'

    @method_decorator(user_passes_test(lambda x: x.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda x: x.is_superuser)
def shopuser_create(request):
    if request.method == 'POST':
        form = ShopUserAdminCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()  # приводит к сохранению в базу данных
            return HttpResponseRedirect(reverse('myadmin:index'))
    else:
        form = ShopUserAdminCreateForm()

    content = {
        'title': 'админка/новый пользователь',
        'form': form,
    }

    return render(request, 'adminapp/shopuser_update.html', content)


@user_passes_test(lambda x: x.is_superuser)
def shopuser_update(request, pk):
    user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        form = ShopUserAdminUpdateForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()  # приводит к сохранению в базу данных
            return HttpResponseRedirect(reverse('myadmin:index'))
    else:
        form = ShopUserAdminUpdateForm(instance=user)

    content = {
        'title': 'админка/редактирование пользователя',
        'form': form,
    }

    return render(request, 'adminapp/shopuser_update.html', content)


@user_passes_test(lambda x: x.is_superuser)
def shopuser_delete(request, pk):
    user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('myadmin:index'))
    elif request.method == 'GET':
        content = {
            'title': 'админка/удаление пользователя',
            'object': user,
        }
        return render(request, 'adminapp/shopuser_delete.html', content)


@user_passes_test(lambda x: x.is_superuser)
def productcategory_list(request):
    object_list = Categories.objects.all()
    content = {
        'title': 'админка/категории',
        'object_list': object_list
    }
    return render(request, 'adminapp/productcategory_list.html', content)


# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_create(request):
#     if request.method == 'POST':
#         form = CategoriesAdminUpdateForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()  # приводит к сохранению в базу данных
#             return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     else:
#         form = CategoriesAdminUpdateForm()
#
#     content = {
#         'title': 'админка/новая категория',
#         'form': form,
#     }
#
#     return render(request, 'adminapp/productcategory_update.html', content)


class ProductCategoryCreateView(CreateView):
    model = Categories
    # template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('myadmin:productcategory_list')
    # fields = '__all__'
    form_class = CategoriesAdminUpdateForm


# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_update(request, pk):
#     productcategory = get_object_or_404(Categories, pk=pk)
#     if request.method == 'POST':
#         form = CategoriesAdminUpdateForm(request.POST, request.FILES, instance=productcategory)
#         if form.is_valid():
#             form.save()  # приводит к сохранению в базу данных
#             return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     else:
#         form = CategoriesAdminUpdateForm(instance=productcategory)
#
#     content = {
#         'title': 'админка/новая категория',
#         'form': form,
#     }
#
#     return render(request, 'adminapp/productcategory_update.html', content)


class ProductCategoryUpdateView(UpdateView):
    model = Categories
    # template_name = 'adminapp/productcategory_list.html'
    success_url = reverse_lazy('myadmin:productcategory_list')
    form_class = CategoriesAdminUpdateForm

    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        content['title'] = 'админка / редактирование категории'
        return content

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.products_set.update(price_product=F('price_product') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)
        return super().form_valid(form)


# @user_passes_test(lambda x: x.is_superuser)
# def productcategory_delete(request, pk):
#     productcategory = get_object_or_404(Categories, pk=pk)
#     if request.method == 'POST':
#         productcategory.is_active = False
#         productcategory.save()
#         return HttpResponseRedirect(reverse('myadmin:productcategory_list'))
#     elif request.method == 'GET':
#         content = {
#             'title': 'админка/удаление категории',
#             'object': productcategory,
#         }
#         return render(request, 'adminapp/productcategory_delete.html', content)

class ProductCategoryDeleteView(DeleteView):
    model = Categories
    success_url = reverse_lazy('myadmin:productcategory_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda x: x.is_superuser)
def productcategory_products(request, pk):
    productcategory = get_object_or_404(Categories, pk=pk)
    content = {
        'title': 'админка/товары категории',
        'productcategory': productcategory,
        'object_list': productcategory.products_set.all(),
    }

    return render(request, 'adminapp/product_list.html', content)


# @user_passes_test(lambda x: x.is_superuser)
# def product_create(request, pk):
#     productcategory = get_object_or_404(Categories, pk=pk)
#     if request.method == 'POST':
#         form = ProductAdminUpdateForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()  # приводит к сохранению в базу данных
#             # return HttpResponseRedirect(reverse('myadmin:productcategory_products', kwargs={'pk': pk}))
#             return HttpResponseRedirect(reverse('myadmin:productcategory_products', args=[pk]))
#     else:
#         form = ProductAdminUpdateForm(initial={'category': productcategory})
#     content = {
#         'title': 'админка/новый товар',
#         'form': form,
#     }
#     return render(request, 'adminapp/product_update.html', content)

@user_passes_test(lambda x: x.is_superuser)
def product_create(request, pk):
    productcategory = get_object_or_404(Categories, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('myadmin:productcategory_products', kwargs={'pk': pk}))
    else:
        form = ProductAdminUpdateForm()
    content = {
        'title': 'админка/новый товар',
        'form': form
    }
    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda x: x.is_superuser)
def product_update(request, pk):
    product = get_object_or_404(Products, pk=pk)
    if request.method == 'POST':
        form = ProductAdminUpdateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()  # приводит к сохранению в базу данных
            return HttpResponseRedirect(reverse('myadmin:productcategory_products', kwargs={'pk': product.category.pk}))
    else:
        form = ProductAdminUpdateForm(instance=product)

    content = {
        'title': 'админка/изменение товара',
        'form': form,
        'object': product,
    }

    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda x: x.is_superuser)
def product_delete(request, pk):
    product = get_object_or_404(Products, pk=pk)
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('myadmin:productcategory_products', kwargs={'pk': product.category.pk}))
    elif request.method == 'GET':
        content = {
            'title': 'админка/удаление товара',
            'object': product,
        }
        return render(request, 'adminapp/product_delete.html', content)


# @user_passes_test(lambda x: x.is_superuser)
# def product_read(request, pk):
#     product = get_object_or_404(Products, pk=pk)
#     content = {
#         'title': 'админка/подробнее о товаре',
#         'object': product
#     }
#     return render(request, 'adminapp/product_read.html', content)


class ProductDetailView(DetailView):
    model = Products

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style_admin.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
    <div class="admin_menu">
        <ul class="menu">
            <li>
                <a href="{% url 'main:main' %}">на сайт</a>
            </li>
            <li>
                <a href="{% url 'myadmin:index' %}"
                   class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                    пользователи
                </a>
            </li>
            <li>
                <a href="{% url 'myadmin:productcategory_list' %}"
                   class="{% if request.resolver_match.url_name == 'productcategory_list' %}active{% endif %}">
                    категории{% if category %}:<span>{{ category.name }}</span>{% endif %}
                </a>
            </li>
        </ul>
    </div>
    {% endblock %}

    {% block container %}
    {% endblock %}

</div>
</body>
</html>

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
<div class="user_delete">
    Уверены, что хотите удалить товар <b>{{ object.name_category }}</b>?
    <form method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <a href="{% url 'myadmin:productcategory_products' object.category.pk %}"
       class="btn btn-primary form-control last">
        к списку товаров
    </a>
</div>
{% endblock %}

adminapp/templates/adminapp/product_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
    <div class="categories_list">
        <h1>Товары категории "{{ productcategory }}"</h1>
        <a href="{% url 'myadmin:product_create' productcategory.pk %}" class="btn btn-primary new_category">Добавить товар</a>
        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img src="/media/{{ object.image_product|default:'products_images/default.jpg' }}"
                     alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name_product|title }}
                </div>
                <div class="product_actions">
                    <a href="{% url 'myadmin:product_read' object.pk %}"
                       class="btn btn-info">
                        подробнее
                    </a>
                    <a href="{% url 'myadmin:product_update' object.pk %}"
                       class="btn btn-success">
                        редактировать
                    </a>
                    <a href="{% url 'myadmin:product_delete' object.pk %}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price_product }} руб</p>
                </div>
                <!--div class="product_desc">
                    {{ object.description_product|title }}
                </div-->
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
<div class="new_category_form">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a href="{% url 'myadmin:productcategory_products' request.resolver_match.kwargs.pk %}"
       class="btn btn-primary form-control last">
        к списку товаров
    </a>
</div>
{% endblock %}

adminapp/templates/adminapp/productcategory_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block container %}
<div class="categories_list">
    <a href="{% url 'myadmin:productcategory_create' %}"
       class="btn btn-primary new_category">
        новая категория
    </a>
    {% for object in object_list %}
    <div class="category_record {% if not object.is_active %}not_active{% endif %}">
        <div class="category_name">
            {{ object.name_category|title }}
        </div>
        <div class="category_actions">
            <a href="{% url 'myadmin:productcategory_products' object.pk %}"
               class="btn btn-info">
                товары категории
            </a>
            <a href="{% url 'myadmin:productcategory_update' object.pk %}"
               class="btn btn-success">
                редактировать
            </a>
            <a href="{% url 'myadmin:productcategory_delete' object.pk %}"
               class="btn btn-danger">
                удалить
            </a>
        </div>
        <div class="category_desc">
            {{ object.description_category }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

adminapp/templates/adminapp/shopuser_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
<div class="user_delete">
    Уверены, что хотите удалить <b>{{ object.username }}
    {% if object.first_name %}
    ({{ object.first_name|title }}
        {% if object.last_name %}
            {{ object.last_name|title }}
        {% endif %})
    {% endif %}</b>?
    <form method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <a href="{% url 'myadmin:index' %}" class="btn btn-success">
        отмена
    </a>
</div>
{% endblock %}

adminapp/templates/adminapp/shopuser_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'myadmin:index' %}"
           class="btn btn-primary form-control last">
            к списку пользователей
        </a>
    </div>
{% endblock %}