authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path, re_path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    re_path(r'^$', basketapp.index, name='index'),
    re_path('add/(?P<pk>\d+)/', basketapp.basket_add, name='add'),
    re_path('delete/(?P<pk>\d+)/', basketapp.basket_delete, name='delete'),
    re_path('update/(?P<pk>\d+)/(?P<quantity>\d+)/', basketapp.basket_update, name='update'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include  # Возможно стоит исправить строку
from django.conf.urls.static import static
from django.urls import path, re_path

urlpatterns = [
    path('myadmin/', include('adminapp.urls', namespace='myadmin')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('category/<int:pk>/', mainapp.category, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.category, name='category_paginator'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('infopage/<int:pk>/', cache_page(3600)(mainapp.infopage), name='infopage'),

    # re_path(r'^category/(?P<pk>\d+)/$', mainapp.category, name='category'),
    # re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    # re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    # path('contacts/', mainapp.contacts, name='contacts'),
    # re_path(r'^infopage/(?P<pk>\d+)/$', mainapp.infopage, name='infopage'),
    # path('catalog/', mainapp.catalog, name='catalog'),
    # re_path(r'^catalog/(\d+)/$', mainapp.catalog, name='catalog'),
    # path('product/', mainapp.product, name='product'),
]

mainapp/models.py
from django.db import models


# Create your models here

class Categories(models.Model):
    name_category = models.CharField(verbose_name='Название категории', max_length=128, unique=True)
    header_category = models.CharField(verbose_name='Заголовок категории', max_length=128, blank=True)
    description_category = models.TextField(verbose_name='Описание категории', blank=True)
    show_in_main_menu = models.BooleanField(verbose_name='Выводить страницу в главном меню?', default=False)
    is_active = models.BooleanField(db_index=True, verbose_name='Показывать категорию', default=True)

    def __str__(self):
        return self.name_category

    class Meta:
        verbose_name_plural = 'Категории товаров'
        verbose_name = 'Категория'
        ordering = ['is_active', 'name_category']


class Products(models.Model):
    name_product = models.CharField(verbose_name='Название товара', max_length=128)
    description_product = models.TextField(verbose_name='Описание товара', blank=True)
    # предварительно pip install pillow
    image_product = models.ImageField(upload_to='images_products', blank=True, default='images_products/no_image.jpg')
    quantity = models.PositiveIntegerField(verbose_name='Кол-во на складе', null=False, default=10)
    price_product = models.PositiveIntegerField(verbose_name='Цена товара', null=False)  # цена больше 0 и без копеек
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    is_new = models.BooleanField(db_index=True, verbose_name='Новый товар', default=False)
    is_discount = models.BooleanField(db_index=True, verbose_name='Товар со скидкой', default=False)
    is_popular = models.BooleanField(db_index=True, verbose_name='Популярный товар', default=False)
    is_exclusive = models.BooleanField(db_index=True, verbose_name='Эксклюзивный товар', default=False)
    is_active = models.BooleanField(db_index=True, verbose_name='Показывать товар', default=True)

    class Meta:
        verbose_name_plural = 'Товары'
        verbose_name = 'Товар'
        ordering = ['is_active', 'name_product']

    def __str__(self):
        return self.name_product

    @staticmethod
    def get_items():
        return Products.objects.filter(is_active=True).order_by('category', 'name_product')


class InfoPages(models.Model):
    name_page = models.CharField(verbose_name='Название страницы', max_length=128, unique=True)
    header_page = models.CharField(verbose_name='Заголовок страницы', max_length=128, blank=True)
    content_page = models.TextField(verbose_name='Контент страницы', blank=True, default='<p></p>')
    show_in_main_menu = models.BooleanField(db_index=True, verbose_name='Выводить страницу в главном меню?', default=False)
    order_in_menu = models.PositiveIntegerField(verbose_name='Номер в меню', default=0)

    class Meta:
        verbose_name_plural = 'Информационные страницы'
        verbose_name = 'Инфостраница'
        ordering = ['name_page']

    def __str__(self):
        return self.name_page

mainapp/views.py
import random
from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
from itertools import chain

from .models import Categories, Products, InfoPages


# Create your views here

# main_menu = [
#     {'href': 'category/1/', 'name': 'Смартфоны'},
#     {'href': '#', 'name': 'Оплата'},
#     {'href': '#', 'name': 'Доставка'},
#     {'href': 'contacts', 'name': 'Контакты'}
# ]

# def main_menu():
#     categories = Categories.objects.filter(show_in_main_menu=True)
#     info_pages = InfoPages.objects.filter(show_in_main_menu=True)
#     main_menu = list(chain(categories, info_pages.order_by('order_in_menu')))
#     return main_menu

def main_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            categories = Categories.objects.filter(show_in_main_menu=True)
            info_pages = InfoPages.objects.filter(show_in_main_menu=True)
            links_menu = list(chain(categories, info_pages.order_by('order_in_menu')))
            cache.set(key, links_menu)
        return links_menu
    else:
        categories = Categories.objects.filter(show_in_main_menu=True)
        info_pages = InfoPages.objects.filter(show_in_main_menu=True)
        links_menu = list(chain(categories, info_pages.order_by('order_in_menu')))
        return links_menu


# def footer_menu():
# #     info_pages = InfoPages.objects.all()
# #     return info_pages

def footer_menu():
    if settings.LOW_CACHE:
        key = 'links_footer_menu'
        links_footer_menu = cache.get(key)
        if links_footer_menu is None:
            links_footer_menu = info_pages = InfoPages.objects.all()
            cache.set(key, links_footer_menu)
        return links_footer_menu
    else:
        return InfoPages.objects.all()


# def get_categories():  # получаем все объекты категорий
#     return Categories.objects.filter(is_active=True)

def get_categories():
    if settings.LOW_CACHE:
        key = 'links_categories'
        links_categories = cache.get(key)
        if links_categories is None:
            links_categories = Categories.objects.filter(is_active=True)
            cache.set(key, links_categories)
        return links_categories
    else:
        return Categories.objects.filter(is_active=True)


# def get_products():  # получаем все объекты товаров
#     return Products.objects.filter(is_active=True)

def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Products.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Products.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_basket(request):
    if request.user.is_authenticated:
        return request.user.basket.all().order_by('product__category')  # из юзера достаем корзину
    else:
        return []


def get_hot_product(request):
    return random.choice(Products.objects.all())


def main(request):
    new_products = Products.objects.filter(is_active=True, is_new=True)
    popular_products = Products.objects.filter(is_active=True, is_popular=True)
    exclusive_products = Products.objects.filter(is_active=True, is_exclusive=True)

    content = {
        'title': 'Главная страница магазина',
        'main_menu': main_menu,
        'info_pages': footer_menu(),
        'products': get_products(),
        'new_products': new_products,
        'popular_products': popular_products,
        'exclusive_products': exclusive_products,
    }
    return render(request, 'mainapp/index.html', context=content)


# def catalog(request):
#     content = {
#         'title': 'Каталог товаров',
#         'header1': 'Как определять категорию? Чтобы загружать соответствующие заголовки и товары.',
#         'main_menu': main_menu,
#         'categories': get_categories(),
#         'products': get_products()
#     }
#     return render(request, 'mainapp/catalog.html', content)

def category(request, pk, page=1):
    pk = int(pk)
    if pk == 1:  # если категория (Все модели с pk = 1), то выводим все товары
        current_category = Categories.objects.get(pk=1)
        # current_category = get_object_or_404(Categories, pk=1)
        products_category = Products.objects.filter(is_active=True)
    else:  # по primary key выводим товары этой категории
        current_category = Categories.objects.filter(pk=pk).first()
        products_category = Products.objects.filter(category=pk, is_active=True)

    paginator = Paginator(products_category, 15)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    content = {
        'title': current_category.header_category,
        'header1': current_category.header_category,
        'main_menu': main_menu(),
        'info_pages': footer_menu(),
        'categories': get_categories(),
        'category': current_category,
        'products': products_paginator,
    }
    return render(request, 'mainapp/catalog.html', content)


def product(request, pk):
    product = Products.objects.get(pk=pk, is_active=True)
    # выбираем похожие товары по категории, исключая текущий товар
    same_products = Products.objects.filter(category=product.category, is_active=True).exclude(pk=pk)
    content = {
        'title': product.name_product,
        'header1': product.name_product,
        'product': product,
        'same_products': same_products,
        'main_menu': main_menu(),
        'info_pages': footer_menu(),
        'categories': get_categories(),
        'products': get_products(),
    }
    return render(request, 'mainapp/product.html', context=content)


def contacts(request):
    content = {
        'title': 'Контакты интернет-магазина MyPhone',
        'header1': 'Контакты магазина',
        'main_menu': main_menu(),
        'info_pages': footer_menu(),
    }
    return render(request, 'mainapp/contacts.html', context=content)


def infopage(request, pk):
    current_page = InfoPages.objects.filter(pk=pk).first()
    content = {
        'page': current_page,
        'title': current_page.header_page,
        'main_menu': main_menu(),
        'info_pages': footer_menu(),
    }
    return render(request, 'mainapp/infopage.html', context=content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/9ece0e8aef.js"></script>
    <link rel="shortcut icon" href="{% static 'images/favicon.jpg' %}" type="image/jpg">
    <title>{% block title_page %}{{ title }}{% endblock %}</title>
</head>

<body>
    <div class="container">

        <div class="top">
            <!-- Header -->
            <div class="{% block type_header %}header_inner_pages{% endblock %} padding_site">
                {% include 'mainapp/includes/inc_main_menu.html' %}
                {% block text_slider %}{% endblock %}
                {% block header1_page %}{{ header1_page|title }}{% endblock %}
            </div>
            {% block content %}
            {% endblock %}
        </div>

        <!-- Footer -->
        {% block footer %}
        <footer class="footer padding_site">
            <div class="footer_first_block">
                <div class="footer_contact_us">
                    <p class="footer_contact_us_title">Наши контакты</p>
                    <p class="footer_contact_us_address">г. Москва,<br>Севастопольский пр-кт, д. 29</p>
                    <p class="footer_contact_us_phone">метро Нагорная, Крымская</p>
                    <p class="footer_contact_us_mail"><a class="footer_contact_us_mail_a" href="mailto:info@myphone.ru" title="Написать письмо">info@myphone.ru</a></p>
                </div>
                {%  include 'mainapp/includes/inc_footer_menu.html' %}
                <div class="footer_subscribe">
                    <p class="footer_subscribe_title">Оставайтесь с нами!</p>
                    <p class="footer_subscribe_description">Подишитесь на рассылку и в числе первых узнаете о выгодных акциях и скидках на телефоны!</p>
                    <form action="#" class="footer_subscribe_form">
                        <input type="email" class="footer_subscribe_input" placeholder="Введите вашу почту" maxlength="43">
                        <a href="#" class="footer_subscribe_button" title="Подписаться на рассылку писем"><i class="fab fa-telegram-plane"></i></a>
                    </form>
                </div>
            </div>
            <div class="footer_second_block">
                <p class="footer_copyright">Житников Тарас &copy; {% now "Y" %} Все права защищены</p>
                <ul class="footer_social_networks">
                    <li class="footer_social_networks_li"><a href="#" class="footer_social_networks_a" title="Перейти на страницу в Instagram"><i class="fab fa-instagram"></i></a></li>
                    <li class="footer_social_networks_li"><a href="#" class="footer_social_networks_a" title="Перейти на страницу в Вконтакте"><i class="fab fa-vk"></i></a></li>
                    <li class="footer_social_networks_li"><a href="#" class="footer_social_networks_a" title="Перейти на страницу в Facebook"><i class="fab fa-facebook-square"></i></a></li>
                    <li class="footer_social_networks_li"><a href="#" class="footer_social_networks_a" title="Перейти на страницу в Одноклассники"><i class="fab fa-odnoklassniki-square"></i></a>
                    </li>
                    <li class="footer_social_networks_li"><a href="#" class="footer_social_networks_a" title="Перейти на страницу в Twitter"><i class="fab fa-twitter-square"></i></a></li>
                </ul>
                <p class="footer_terms_privacy">
                    <a href="#" class="footer_terms_privacy_a">Правила обслуживания</a> / <a href="#" class="footer_terms_privacy_a">Конфиденциальность</a>
                </p>
            </div>
        </footer>
        {% endblock %}
    </div>
</body>

</html>

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block header1_page %}<h1 class="title_inner_page">{{ header1 }}</h1>{% endblock %}
{% block content %}
<!-- Trending products -->
<div class="trending_products padding_site">
    <div class="trending_products">
        <ul class="trending_products_menu">
            {% for category in categories %}
            <li class="trending_products_menu_li">
                <a href="{% url 'main:category' category.pk %}"
                   class="trending_products_menu_a{% if request.resolver_match.url_name == category.link_category or request.resolver_match.kwargs.pk|add:0 == category.pk %}_current
                   {% endif %}">{{ category.name_category }}</a>
            </li>
            {% endfor %}
            <!-- li class="trending_products_menu_li"><a href="#" class="trending_products_menu_a_current">Все iPhone</a></li>
            <li class="trending_products_menu_li"><a href="#" class="trending_products_menu_a">6</a></li-->
        </ul>
    </div>

    <!-- Products -->
    <ul class="trending_products_6_products_ul">
        {% for product in products %}
        <li class="trending_products_6_products_product_li">
            <a href="{% url 'main:product' product.pk %}" class="trending_products_6_products_product_a"
               title="{{ product.name_product }} - {{ product.price_product }} руб.">
                <img src="/media/{{ product.image_product }}" alt="{{ product.name_product }}"
                     class="trending_products_6_products_product_img">
            </a>
        </li>
        {% endfor %}
    </ul>

    <div class="paginator trending_products_load">
        {% if products.has_previous %}
        <a href="{% url 'main:category_paginator' category.pk products.previous_page_number %}">< Предыдущая</a>
        {% endif %}
        | <span class="current">Cтраница {{ products.number }} из {{ products.paginator.num_pages }}</span> |
        {% if products.has_next %}
        <a href="{% url 'main:category_paginator' category.pk products.next_page_number %}">Следующая ></a>
        {% endif %}
    </div>

    <!--div class="trending_products_load"><a href="#" class="trending_products_load_a" title="Загрузить еще товары"><i
            class="fas fa-sync-alt"></i></a></div-->
</div>

{% include 'mainapp/includes/inc_2_banners.html' %}
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block type_header %}slider{% endblock %}
{% block text_slider %}
<div class="header_textarea">
    <span class="header_textarea_mini_title">Будь в тренде</span>
    <p class="header_textarea_main_title">iPhone XR</p>
    <p class="header_textarea_text">Лучший iPhone из когда-либо созданных. Самые передовые технологии в новом корпусе.
        Новый iPhone XR</p>
    <a href="/product/11/" class="header_textarea_button_slider">Подробнее ></a>
</div>

<div class="pagination_slider">
    <a href="#" class="pagination_slider_a"></a>
    <a href="#" class="pagination_slider_a_current"></a>
    <a href="#" class="pagination_slider_a"></a>
</div>
{% endblock %}
{% block content %}
<!-- Featured products -->
<div class="featured_products padding_site">
    <div class="featured_products_navigation">
        <div class="featured_products_navigation_tabs">
            <a href="#" class="featured_products_navigation_tab_active">Новинки</a><a href="#"
                                                                                      class="featured_products_navigation_tab">Скидки</a>
        </div>
        <a href="{% url 'main:category' 1 %}" class="products_explore_all">Все модели ></a>
    </div>

    <ul class="featured_products_4_products_ul">
        {% for product in new_products|slice:":4" %}
        <li class="featured_products_4_products_product_li"
            style="background-image: url('/media/{{ product.image_product }}');">
            <div class="featured_products_4_products_product_description">
                <a href="{% url 'main:product' product.pk %}" class="featured_products_4_products_product_description_button">></a>
                <span class="featured_products_4_products_product_description_title">{{ product.name_product }}</span>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

{% include 'mainapp/includes/inc_2_banners.html' %}

<!-- Trending products -->
<div class="trending_products padding_site">
    <div class="trending_products_titles">
        <span class="trending_products_title">Популярные модели iPhone</span>
        <a href="{% url 'main:category' 1 %}" class="products_explore_all">Все модели ></a>
    </div>
    <ul class="trending_products_6_products_ul">
        {% for product in popular_products|slice:":6" %}
        <li class="trending_products_6_products_product_li">
            <a href="{% url 'main:product' product.pk %}" class="trending_products_6_products_product_a"
               title="{{ product.name_product }} - {{ product.price_product }} руб.">
                <img src="/media/{{ product.image_product }}" alt="{{ product.name_product }}"
                     class="trending_products_6_products_product_img">
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

<!-- Hot deal slider -->
<div class="hot_deal_slider padding_site">
    <div></div>
    <div class="hot_deal_slider_textarea">
        <span class="hot_deal_slider_textarea_mini_title">Новая</span>
        <p class="hot_deal_slider_textarea_main_title">Коллекция XR</p>
        <p class="hot_deal_slider_textarea_text">Представляем новинку 2019 года! Коллекция самых современных iPhone XR в красочных цветах.</p>
        <a href="/category/8/" class="hot_deal_slider_textarea_button_slider">Восхититься;)</a>
    </div>

    <div class="pagination_slider">
        <a href="#" class="pagination_slider_a"></a>
        <a href="#" class="pagination_slider_a_current"></a>
        <a href="#" class="pagination_slider_a"></a>
    </div>
</div>

<!-- Exclusive 5 products -->
<div class="trending_products padding_site">
    <div class="trending_products_titles">
        <span class="trending_products_title">Эксклюзивные модели</span>
    </div>

    <div class="exclusive_5_products">
        <div class="exclusive_5_products_block1">
            <div class="exclusive_5_products_block_textarea">
                <span class="exclusive_products_block_textarea_mini_title">Эксклюзив</span>
                <p class="exclusive_products_block_textarea_main_title">Голубой XR</p>
                <p class="exclusive_products_block_textarea_text">Новый цвет XR. Впервые в истории Apple небесно-голубой iPhone.</p>
                <a href="/product/13/" class="exclusive_products_block_textarea_button">Посмотреть ></a>
            </div>
        </div>

        <ul class="exclusive_5_products_block2">
            {% for product in exclusive_products|slice:":4" %}
            <li class="featured_products_4_products_product_li"
                style="background-image: url('/media/{{ product.image_product }}');">
                <div class="featured_products_4_products_product_description">
                    <a href="{% url 'main:product' product.pk %}" class="featured_products_4_products_product_description_button">></a>
                    <span class="featured_products_4_products_product_description_title">{{ product.name_product }}</span>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

<!-- Banner of application -->
<div class="banner_mobile_app padding_site">
    <div class="banner_mobile_app_textarea">
        <span class="banner_mobile_app_textarea_mini_title">Мобильное приложение</span>
        <p class="banner_mobile_app_textarea_main_title">Находи. Выбирай.<br>Покупай.</p>
        <p class="banner_mobile_app_textarea_text">Наш магазин всегда под рукой.</p>
    </div>
    <div class="banner_mobile_app_buttons">
        <a href="#" class="banner_mobile_app_textarea_button_app_store" title="Скачать приложение в App Store"><img
                src="{% static 'images/img_app_store.jpg' %}" alt="Скачать приложение в App Store"></a>
        <a href="#" class="banner_mobile_app_textarea_button_google_play" title="Скачать приложение в Google Play"><img
                src="{% static 'images/img_google_play.jpg' %}" alt="Скачать приложение в Google Play Market"></a>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/infopage.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block header1_page %}<h1 class="title_inner_page">{{ page.header_page }}</h1>{% endblock %}
{% block content %}
{{ page.content_page|safe }}
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block type_header %}header_product{% endblock %}
{% block content %}
<nav class="navigation_product">
    <ul class="navigation_product_menu">
        {% for category in categories %}
        <li class="navigation_product_menu_li">
            <a href="{% url 'main:category' category.pk %}"
               class="navigation_product_menu_a">{{ category.name_category }}</a>
        </li>
        {% endfor %}
    </ul>
</nav>

<main>
    <div class="content_product padding_site">
        <div class="content_product_image_block">
            <a href="#" class="content_product_image_block_a" title="Увеличить изображение"><img
                    src="/media/{{ product.image_product }}" alt="Главное изображение товара"
                    class="content_product_image_block_img"></a>
            <!--ul class="content_product_image_block_preview_list">
                <li class="content_product_image_block_preview_list_li">
                    <a href="#" class="content_product_image_block_preview_list_a">
                        <img src="{% static 'images/other_img_product_blue.jpg' %}" alt=""
                             class="content_product_image_block_preview_list_img">
                    </a>
                </li>
                <li class="content_product_image_block_preview_list_li">
                    <a href="#" class="content_product_image_block_preview_list_a">
                        <img src="{% static 'images/other_img_product_lightblue.jpg' %}" alt=""
                             class="content_product_image_block_preview_list_img">
                    </a>
                </li>
                <li class="content_product_image_block_preview_list_li">
                    <a href="#" class="content_product_image_block_preview_list_a">
                        <img src="{% static 'images/other_img_product_blue.jpg' %}" alt=""
                             class="content_product_image_block_preview_list_img">
                    </a>
                </li>
                <li class="content_product_image_block_preview_list_li">
                    <a href="#" class="content_product_image_block_preview_list_a">
                        <img src="{% static 'images/other_img_product_lightblue.jpg' %}" alt=""
                             class="content_product_image_block_preview_list_img">
                    </a>
                </li>
            </ul-->
        </div>
        <div class="content_product_info_block">
            <h1 class="content_product_info_block_title">{{ product.name_product }}</h1>
            {% if product.is_new %}
            <p class="content_product_info_block_grey_label">Новинка</p>
            {% endif %}
            {% if product.is_discount %}
            <p class="content_product_info_block_red_label">Распродажа</p>
            {% endif %}
            {% if product.is_exclusive %}
            <p class="content_product_info_block_purple_label">Эксклюзив</p>
            {% endif %}
            {% if product.is_popular %}
            <p class="content_product_info_block_green_label">Популярная модель</p>
            {% endif %}
            <p>На складе: {{ product.quantity }}</p>
            <div class="content_product_info_block_price">
                <p class="content_product_info_block_price_numbers">{{ product.price_product|floatformat:"0" }} <span
                        class="content_product_info_block_price_currency">руб.</span></p>
            </div>
            <a href="{% url 'basket:add' product.pk %}" class="content_product_info_block_button">Купить ></a>
            <div class="content_product_info_block_description">
                <p>{{ product.description_product }}</p>
            </div>
        </div>
    </div>
</main>

<!-- The same products -->
<div class="trending_products padding_site">
    <div class="trending_products_titles">
        <span class="trending_products_title">Похожие смартфоны</span>
        <a href="{% url 'main:category' 1 %}" class="products_explore_all">Все модели ></a>
    </div>
    <ul class="trending_products_6_products_ul">
        {% for product in same_products|slice:":3" %}
        <li class="trending_products_6_products_product_li">
            <a href="{% url 'main:product' product.pk %}" class="trending_products_6_products_product_a"
               title="{{ product.name_product }} - {{ product.price_product }} руб.">
                <img src="/media/{{ product.image_product }}" alt="{{ product.name_product }}"
                     class="trending_products_6_products_product_img">
            </a>
            {% endfor %}
        </li>
    </ul>
</div>
{% endblock %}