authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', authapp.login, name='login'),
    re_path(r'^logout/$', authapp.logout, name='logout'),
    re_path(r'^register/$', authapp.register, name='register'),
    re_path(r'^update/$', authapp.update, name='update'),
    # re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include  # Возможно стоит исправить строку
from django.conf.urls.static import static
from django.urls import path, re_path

urlpatterns = [
    path('myadmin/', include('adminapp.urls', namespace='myadmin')),
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('category/<int:pk>/', mainapp.category, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.category, name='category_paginator'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('infopage/<int:pk>/', cache_page(3600)(mainapp.infopage), name='infopage'),

    # re_path(r'^category/(?P<pk>\d+)/$', mainapp.category, name='category'),
    # re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/$', mainapp.category, name='category_paginator'),
    # re_path(r'^product/(?P<pk>\d+)/$', mainapp.product, name='product'),
    # path('contacts/', mainapp.contacts, name='contacts'),
    # re_path(r'^infopage/(?P<pk>\d+)/$', mainapp.infopage, name='infopage'),
    # path('catalog/', mainapp.catalog, name='catalog'),
    # re_path(r'^catalog/(\d+)/$', mainapp.catalog, name='catalog'),
    # path('product/', mainapp.product, name='product'),
]

ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import re_path

app_name = "ordersapp"

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price),
]

ordersapp/models.py
from django.db import models
from django.conf import settings

from mainapp.models import Products


# Create your models here.

class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'заказ формируется'),
        (SENT_TO_PROCEED, 'отправлен в обработку'),
        (PAID, 'заказ оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готов к выдаче'),
        (CANCEL, 'заказ отменен'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='Заказ создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Заказ обновлен', auto_now=True)
    status = models.CharField(verbose_name='Статус заказа', max_length=3, choices=ORDER_STATUS_CHOICES, default=FORMING)
    is_active = models.BooleanField(verbose_name='Активен', default=True)

    class Meta:
        ordering = ('-created',)  # сортировка по умолчанию от более новых к старым заказам
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Текущий заказ: {}'.format(self.id)

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    # def get_total_quantity(self):
    #     items = self.orderitems.select_related()
    #     return sum(list(map(lambda x: x.quantity, items)))
    #
    # def get_total_cost(self):
    #     items = self.orderitems.select_related()
    #     return sum(list(map(lambda x: x.quantity * x.product.price_product, items)))

    # Вместо двух методов get_total_quantity() и get_total_cost() создадим один get_summary(), возвращающий словарь:
    def get_summary(self):
        items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.quantity * x.product.price_product, items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, items)))
        }

    # переопределяем метод, удаляющий объект
    def delete(self):
        for item in self.orderitems.select_related():  # находим все элементы заказа
            item.product.quantity += item.quantity  # корректируем остатки продуктов на складе
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    # Доступ к элементам заказа через атрибут orderitems возможен благодаря аргументу related_name
    order = models.ForeignKey(Order, related_name="orderitems", on_delete=models.CASCADE)
    product = models.ForeignKey(Products, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price_product * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem
from mainapp.models import Products


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        # вместо разрешенных полей, прописываем кортежи с полями, которые необходимо исключить из форм
        exclude = ('user',)  # Не забывайте ставить запятую, даже если одно значение в кортеже

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemForm(forms.ModelForm):
    # Добавляем поле «price» к форме элемента заказа
    # Так как это поле не должно сохраняться в базу и проходить валидацию - задаем аргумент required=False
    price = forms.CharField(label='Цена за единицу', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(OrderItemForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['product'].queryset = Products.get_items()

ordersapp/views.py
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import JsonResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.dispatch import receiver
from django.db.models.signals import pre_save, pre_delete
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import F

from mainapp.models import Products
from basketapp.models import Basket
from ordersapp.models import Order, OrderItem
from ordersapp.forms import OrderItemForm


# Create your views here.

class OrderList(ListView):
    model = Order

    # Переопределили метод get_queryset(), чтобы пользователь видел только свои заказы
    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(ListView, self).dispatch(*args, **kwargs)


class OrderItemsCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    # необходимо передать набор форм в шаблон
    def get_context_data(self, **kwargs):
        data = super(OrderItemsCreate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            # Получаем объекты корзины пользователя
            basket_items = Basket.get_items(self.request.user)
            if len(basket_items):
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=len(basket_items))
                formset = OrderFormSet()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price_product
                basket_items.delete()
            else:  # Если корзина пустая - создаем набор с одной чистой формой
                formset = OrderFormSet()
        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']
        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
        # удаляем пустой заказ
        # if self.object.get_total_cost() == 0:
        total_cost = self.object.get_summary()
        if total_cost['total_cost'] == 0:
            self.object.delete()
        return super(OrderItemsCreate, self).form_valid(form)

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(CreateView, self).dispatch(*args, **kwargs)


class OrderRead(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderRead, self).get_context_data(**kwargs)
        context['title'] = 'заказ/просмотр'
        return context

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(DetailView, self).dispatch(*args, **kwargs)


class OrderItemsUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:orders_list')

    def get_context_data(self, **kwargs):
        data = super(OrderItemsUpdate, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)
        if self.request.POST:
            data['orderitems'] = OrderFormSet(self.request.POST, instance=self.object)
        else:
            # data['orderitems'] = OrderFormSet(instance=self.object)
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price_product
            data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']
        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()
        # удаляем пустой заказ
        # if self.object.get_total_cost() == 0:
        total_cost = self.object.get_summary()
        if total_cost['total_cost'] == 0:
            self.object.delete()
        return super(OrderItemsUpdate, self).form_valid(form)

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(UpdateView, self).dispatch(*args, **kwargs)


def get_product_price(request, pk):
    if request.is_ajax():
        product = Products.objects.filter(pk=int(pk)).first()
        if product:
            return JsonResponse({'price': product.price_product})
        else:
            return JsonResponse({'price': 0})


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('ordersapp:orders_list')

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(DeleteView, self).dispatch(*args, **kwargs)


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SENT_TO_PROCEED
    order.save()

    return HttpResponseRedirect(reverse('ordersapp:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_save(sender, update_fields, instance, **kwargs):
    if update_fields is 'quantity' or 'product':
        # Проверяем, новый это объект или уже существующий
        if instance.pk:
            instance.product.quantity -= F('quantity') - sender.get_item(instance.pk).quantity
        else:
            instance.product.quantity = F('quantity') - 1
        instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_delete(sender, instance, **kwargs):
    instance.product.quantity = F('quantity') + 1
    instance.product.save()

ordersapp/templates/ordersapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{{ title|title }}{% endblock %}</title>
        {% block css %}
            <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'css/style_admin.css' %}">
        {% endblock %}
        {% block js %}
            <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
            <script src="{% static 'js/jquery.formset.js' %}"></script>
            <script src="{% static 'js/orders_scripts.js' %}"></script>
        {% endblock %}
    </head>
    <body>
        <div class="order_container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="category_delete">
    <div class="h1">Уверены, что хотите удалить?</div>
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <form action="{% url 'ordersapp:order_delete' object.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'ordersapp:orders_list' %}">отмена</a>
    </button>
</div>
{% endblock %}

ordersapp/templates/ordersapp/order_detail.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load my_tags %}

{% block content %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
<div class="basket_list">
    {% for item in object.orderitems.select_related %}
    <div class="basket_record">
        <img src="{{ item.product.image|media_folder_products }}" alt="{{ item.product.short_desc }}">
        <span class="product_name">{{ item.product.name_product }}</span>
        <span class="product_price">{{ item.product.price_product }} руб.</span>
        <span class="product_quantitiy">x {{ item.quantity }} шт.</span>
        <span class="product_cost">= {{ item.get_product_cost }}руб.</span>
    </div>
    {% endfor %}
</div>
{% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

ordersapp/templates/ordersapp/order_form.html
{% extends "ordersapp/base.html" %}
{% load static %}
{% load cache %}

{% block content %}
{% include 'ordersapp/includes/inc_order_summary.html' %}
<div class="order_form">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <table class="table">
            {{ orderitems.management_form }}
            {% for form in orderitems.forms %}
            {% if forloop.first %}
            <thead>
            <tr>
                {% for field in form.visible_fields %}
                <th class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                    {{ field.label|capfirst }}
                </th>
                {% endfor %}
            </tr>
            </thead>
            {% endif %}
            <tr class="formset_row">
                {% for field in form.visible_fields %}
                <td class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                    {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {% if field.name != 'price' %}
                        {% if field.name == 'product' %}
                            {% cache 3600 orderitemform_product field.value %}
                                {{ field }}
                            {% endcache %}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% else %}
                        <!-- Если для данного поля цена не задана (для нового элемента заказа) -->
                        {% if field.value %}
                            <span class="orderitems-{{forloop.parentloop.counter0}}-price">{{ field.value }}</span> руб.
                        {% endif %}
                    {% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </table>
        <button type="submit" value="сохранить" class="btn btn-default btn-round form-control last">сохранить</button>
        {% include 'ordersapp/includes/inc_order_actions.html' %}
    </form>
</div>

{% endblock %}

ordersapp/templates/ordersapp/order_list.html
{% extends 'ordersapp/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="h2 text-center head">Ваши заказы,
    {% if user.first_name %}
        {{ user.first_name|title}}
    {% else %}
        Пользователь
    {% endif %}
</div>

<table class="table orders_list">
    <thead>
    <tr>
        <th>ID</th>
        <th>Создан</th>
        <th>Обновлен</th>
        <th>Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for item in object_list %}
    <!-- Показываем в списке только активные заказы -->
    {% if item.is_active %}
    <tr>
        <td class="td1 orders_list">{{ item.pk }}</td>
        <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
        <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
        <!-- Для корректного отображения атрибута модели с выбором из списка значений -->
        <td>{{ item.get_status_display }}</td>
        <td><a href="{% url 'ordersapp:order_read' item.pk %}">посмотреть</a></td>
        <td>
            <!-- Некоторые действия доступны только на стадии формирования -->
            {% if item.status == 'FM' %}
            <a href="{% url 'ordersapp:order_update' item.pk %}">редактировать</a>
            {% endif %}
        </td>
        <td>
            {% if item.status == 'FM' %}
            <a href="{% url 'ordersapp:order_delete' item.pk %}">удалить</a>
            {% endif %}
        </td>
    </tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>
<button class="btn btn-default btn-round">
    <a href="{% url 'ordersapp:order_create' %}">Создать новый заказ</a>
</button>
<button class="btn btn-default btn-round">
    <a href="{% url 'main:main' %}">Вернуться на сайт</a>
</button>
{% endblock %}